version: '3.4'

services:
  nasaimage:
    build:
        context: .
        dockerfile: DockerFile
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
